targets = []


[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = []


[licenses]
unlicensed = "deny"
allow = [
  "MIT",
  "Apache-2.0"
]
deny = []
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = false
registries = []


[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
allow = [
  #{ name = "ansi_term", version = "=0.11.0" },
]
deny = [
  
]

skip = [
  #{ name = "ansi_term", version = "=0.11.0" },
]

skip-tree = [
  #{ name = "ansi_term", version = "=0.11.0", depth = 20 },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []