name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version (major / minor / patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target
            Cargo.lock
          key: bump-version-rust

      - name: Install Rust (Stable)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install cargo edit
        run: cargo install cargo-edit

      - name: Bump version
        run: |
          cargo set-version --locked --workspace --bump ${{ github.event.inputs.version }}
          VERSION_NAME=v$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "iqoption-rs") | .version')

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump version to ${VERSION_NAME}"
          title: "Bump version to ${VERSION_NAME}"
          body: "Bump version to ${VERSION_NAME}"
          branch: "${VERSION_NAME}"
          base: "main"
          delete-branch: false
