name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version (major / minor / patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create new branch
        run: |
          OLD_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "iqoption-rs") | .version')
          OLD_BRANCH_NAME=bump-${OLD_VERSION}-with-${{ github.event.inputs.version }}
          git checkout -b $OLD_BRANCH_NAME

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target
            Cargo.lock
          key: bump-version-rust

      - name: Install Rust (Stable)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install cargo edit
        run: cargo install cargo-edit

      - name: Bump version
        run: cargo set-version --locked --workspace --bump ${{ github.event.inputs.version }}

      - name: Commit version
        run: |
          git add .
          git commit -m "Bump version with ${{ github.event.inputs.version }} option"

      - name: Create Version Branch
        run: |
          VERSION_NAME=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "iqoption-rs") | .version')
          BRANCH_NAME=v$(echo $VERSION_NAME)
          git branch -M $OLD_BRANCH_NAME $BRANCH_NAME

      - name: Create tag for version
        run: |
          git tag -a "v${VERSION_NAME}" -m "v${VERSION_NAME}"

      - name: Push latest version
        run: git push --set-upstream origin $BRANCH_NAME:$BRANCH_NAME --follow-tags
