name: Code Coverage
on:
  pull_request:

jobs:
  publish-coverage:
    name: Publish coverage
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
