name: Managment
on: workflow_dispatch

jobs:
  publish-crates:
    name: Publish crates
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-publish-crates

      - name: Install cargo-mono
        continue-on-error: true
        run: |
          cargo install cargo-mono

      - name: Login
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish crates
        run: |
          cargo mono publish