# Called when a new tag and release is created

on:
  release:
    types: [created]
    tags:
      - v*

name: Publish Crate

jobs:
  # Publish in crates.io with the tag
  publish:
    name: Publish in Crates
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-publish-crates

      - name: Install cargo-mono
        continue-on-error: true
        run: |
          cargo install cargo-mono

      - name: Login
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish crates
        run: |
          cargo mono publish
